[package]
name = "tt-weave"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "^3.1", features = ["derive"] }
lazy_static = "^1.4"
lexical-sort = "^0.3"
nom = "^7.1"
nom_locate = "^4.0"
nom-recursive = "^0.4"
syntect = "^4.6"
tectonic_errors = "^0.2"
